package:
  name: d2to1 
  version: "0.2.11"

source:
  fn: d2to1-0.2.11.tar.gz
  url: https://pypi.python.org/packages/source/d/d2to1/d2to1-0.2.11.tar.gz 

build:
  number: 1
  script: python setup.py install

  preserve_egg_dir: True

requirements:
  build:
   - python
   - setuptools

  run:
   - python
   - setuptools

about:
  home: https://pypi.python.org/pypi/d2to1
  summary: Allows using distutils2-like setup.cfg files for a package's metadata with a distribute/setuptools setup.py   
