package:
  name: stsci_distutils
  version: "0.3.7"

source:
  fn: stsci.distutils-0.3.7.tar.gz
  url: https://pypi.python.org/packages/source/s/stsci.distutils/stsci.distutils-0.3.7.tar.gz 

build:
  number: 1
  script: python setup.py install

  preserve_egg_dir: True 

requirements:
  build:
   - python 2.7.*
   - d2to1
  run:
   - python

about:
  home: http://www.stsci.edu/institute/software_hardware/pyfits/
  summary: This package contains utilities used to package some of STScI's Python projects   
